FROM python:3.10
RUN apt update
RUN apt install -y ffmpeg curl
COPY older_bark_voice_clone /project/older_bark_voice_clone
WORKDIR /project/older_bark_voice_clone
RUN pip install fairseq
RUN pip install audiolm-pytorch
RUN pip install .
