FROM python:3.10
RUN apt update
RUN apt install -y ffmpeg curl
COPY bark-with-voice-clone /project/bark-with-voice-clone
WORKDIR /project/bark-with-voice-clone
RUN pip install fairseq
RUN pip install audiolm-pytorch
RUN pip install .
RUN pip install soundfile
